version: '2'
services:
    export-interleaved-doc:
        environment:
            - IRG_OUTPUT_DIR
            - IRG_CS_USER_URL
            - TN_ADDITIONAL_PARMS
            - PYTHONDONTWRITEBYTECODE=1
            - FLASK_APP=/tools/flask_app.py
            - FLASK_DEBUG=1
            - PYTHONUNBUFFERED=1
            - IN_CONTAINER=1
        build: .
        volumes:
            - "${IRG_OUTPUT_DIR}:/output"
        entrypoint:
        - flask
        - run
        - --host=0.0.0.0
        - --port=80
        ports:
        - "5005:80"
